server:
  port: 7100
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 8192
spring:
  datasource:
    jdbc-url: jdbc:mysql://xxxx:3306/userCenter?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: xxxx
    timeout: 5000ms
    port: 6379
    lettuce:
      pool:
        max-idle: 10
        max-active: 10
        min-idle: 1
  http:
    encoding:
      charset: utf-8
      enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: false
  jackson:
      serialization:
        indent_output: true
  mail:
    # 邮箱服务器地址，这里使用的是163.com的邮件服务器
      host: smtp.163.com
    # 在163.com注册的用户名，注意这里不需要@163.com后缀
      username: zhuaizhazha
    # 在163.com使用的授权码(关闭授权码时使用密码)，需要开启POP3/SMTP服务
      password: ARNTJROKMRDJWKMF
      port: 465
      default-encoding: UTF-8
debug: false